Sync Changes for CDK v2
aws/aws-for-fluent-bit pull request #621
Opened 2023-03-31 23:39 UTC by ShelbyZ

*Description of changes:*

- Move python value to 3.x to support existing CDK v1 sync tasks (only support up to 3.9) and CDK v2 sync tasks (support starts with 3.10)
- Avoids needing to update all sync tasks to CDK v2 immediately

This was tested in an AWS account against CDK v1 and v2 deployments without issues.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-04 01:00 UTC, matthewfala approved these changes
Looks good!

2023-04-04 22:39 UTC, PettitWesley commented on buildspec_sync.yml
> +      python: 3.x
I think this doesn't work in gov cloud or china... I think we've tried this before... unless something has changed... let's check the git blame

2023-04-04 22:41 UTC, PettitWesley commented on buildspec_sync.yml
> +      python: 3.x
See here: https://github.com/aws/aws-for-fluent-bit/commit/edbbb2c92f1bb495da45f57d538c84d6858e1ae8

2023-04-04 22:41 UTC, PettitWesley commented on buildspec_sync.yml
> +      python: 3.x
I doubt they have changed it

2023-04-04 22:43 UTC, PettitWesley requested changes
https://github.com/aws/aws-for-fluent-bit/commit/edbbb2c92f1bb495da45f57d538c84d6858e1ae8

I am worried this still won't work in gov cloud

2023-04-04 22:43 UTC, PettitWesley commented
> Avoids needing to update all sync tasks to CDK v2 immediately

Why not update them all in one deployment??

2023-04-06 13:43 UTC, ShelbyZ commented
> [edbbb2c](https://github.com/aws/aws-for-fluent-bit/commit/edbbb2c92f1bb495da45f57d538c84d6858e1ae8)
> 
> I am worried this still won't owrk in gov cloud

after checking gov-cloud on both cdk v1 and v2 it does look like python: 3.x is not supported as a feature for either

2023-04-07 21:15 UTC, ShelbyZ commented
When this change is approved, we will need to update all sync tasks from CDK v1 to v2. CDK v1 will not be able to find an image that satisfies 3.10 (3.9 is the latest) and will cause the tasks to fail pulling new images.

2023-07-20 21:07 UTC, PettitWesley commented on buildspec_sync.yml
> +      python: 3.10
python 3.9 instead

2023-07-20 21:14 UTC, PettitWesley commented
We should check of python 3.10 now exists in codebuild gov cloud

2023-07-31 18:47 UTC, PettitWesley approved these changes
We realized we don't use CDK in sync tasks, and mostly do not use python, so we can just merge this.

2023-08-16 20:23 UTC, matthewfala commented
3.10 will NOT work in existing codebuild projects due to python 3.10 support not found in codebuild image STANDARD_2.

3.10 will require an infrastructure update across all sync accounts.

2023-08-16 20:23 UTC, matthewfala commented
Closing as this PR will break the existing sync tasks without an infra update.

2023-08-16 20:23 UTC, closed without merging